### ISSUE TITLE
Can you include instructions or a small shell script for someone who has never worked with Go Lang?

### ISSUE THREAD

**Issue by ibnYusrat** [felicianotech/go-lguf#3]
I think it would be very nice to have a script, or something like that to set the brighness to 25% - 50% or 100% without having to write any script.. Is it possible? how do I execute the example script that you provided in your README?

**Comment by FelicianoTech** [comment]
Hey. Apologies for replying years later. I was going to get this project back going but I have since found a better solution. Check out this project's readme: https://github.com/felicianotech/go-lguf
